#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -t 1 ]; then
  exec < /dev/tty
fi

yarn test
yarn lint-staged

echo 'Do you want to version this update?'
PS3='Answer: '
TMOUT=10

do_suspend=true

while true; do
        if ! read -p "$PS3"; then
                # timeout
                break
        fi

        case $REPLY in
                "yes")
                        yarn changeset
                        git add .changeset/*
                        break ;;
                "no")
                        do_suspend=false
                        break ;;
                *)
                        echo "invalid option $REPLY";;
        esac
done



#echo 'Do you want to version this update?'
#PS3='Answer: '
#options=("yes" "no")
#
#select opt in "${options[@]}"
#while true; do
#    case $opt in
#        "yes")

#        "no")
#            exit 0
#            ;;
#        *) echo "invalid option $REPLY";;
#    esac
#done
#exit 0
