name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 12
        uses: actions/setup-node@master
        with:
          node-version: 12
          always-auth: true

      - name: Install Dependencies
        run: yarn install --verbose --prod --flat & yarn install --verbose --dev-dependencies

      - name: Lint
        run: yarn lint-staged

      - name: Test
        run: yarn test

      - name: Publish to npm
        uses: changesets/action@master
        with:
          publish: yarn release
          version: yarn version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
